<!DOCTYPE NEWSPAPER [ 

<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)> 

<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>

]>

<NEWSPAPER>
	<ARTICLE AUTHOR="123" EDITOR="123">
		<HEADLINE>abc</HEADLINE>
		<BYLINE>1212</BYLINE>
		<LEAD>dfdf</LEAD>
		<BODY>343</BODY>
		<NOTES>sdsdf</NOTES>
	</ARTICLE>
	<ARTICLE AUTHOR="123">
		<HEADLINE>abc</HEADLINE>
		<BYLINE>1212</BYLINE>
		<LEAD>dfdf</LEAD>
		<BODY>343</BODY>
		<NOTES>sdsdf</NOTES>
	</ARTICLE>
</NEWSPAPER>

